import 'package:path/path.dart' as p;

import 'discovered_preview.dart';

/// Renders the discovered previews as a Dart library exposing
/// `discoveredMockupSpecs()`.
///
/// Generated rather than reflected: Dart has no reflection in AOT or in
/// `flutter test`, so the only way a preview declared beside its widget can
/// reach the harness is for something to have written the reference down.
/// Keeping that file generated and gitignored is what makes adding a preview a
/// one-annotation change with no registry to remember.
///
/// [outDir] is the directory the registry will be written to: a preview under
/// `tool/` has no `package:` URI, so it is imported by a path relative to the
/// generated file rather than by an absolute one, which is not a valid import.
String emitRegistry(
  List<DiscoveredPreview> previews, {
  required String outDir,
}) {
  final Map<String, String> prefixes = _prefixes(previews);
  final StringBuffer out = StringBuffer()
    ..writeln('// GENERATED BY `dart run design_mockups:scan` — DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Every @MockupPreview in the scanned roots, collected into')
    ..writeln('// the specs the harness renders. Regenerated on every render,')
    ..writeln('// so an annotation added or removed needs no other edit.')
    ..writeln('// ignore_for_file: type=lint, unused_import')
    ..writeln()
    ..writeln("import 'package:design_mockups/design_mockups.dart';")
    ..writeln("import 'package:flutter/widgets.dart';");
  for (final String uri in prefixes.keys) {
    out.writeln("import '${_importOf(uri, outDir)}' as ${prefixes[uri]};");
  }
  out
    ..writeln()
    ..writeln('/// The specs discovered by the last scan.')
    ..writeln('List<MockupSpec> discoveredMockupSpecs() => <MockupSpec>[');
  _groupBy(previews, (DiscoveredPreview e) => e.spec).forEach((
    String slug,
    List<DiscoveredPreview> screens,
  ) {
    _writeSpec(out, slug: slug, previews: screens, prefixes: prefixes);
  });
  out.writeln('];');
  return out.toString();
}

/// One import prefix per source library, assigned in a stable order.
Map<String, String> _prefixes(List<DiscoveredPreview> previews) {
  final List<String> uris =
      previews.map((DiscoveredPreview e) => e.importUri).toSet().toList()
        ..sort();
  return <String, String>{for (int i = 0; i < uris.length; i++) uris[i]: 'p$i'};
}

String _importOf(String uri, String outDir) => uri.startsWith('package:')
    ? uri
    : p.relative(uri, from: outDir).replaceAll(r'\', '/');

void _writeSpec(
  StringBuffer out, {
  required String slug,
  required List<DiscoveredPreview> previews,
  required Map<String, String> prefixes,
}) {
  out
    ..writeln('  MockupSpec(')
    ..writeln("    slug: '$slug',")
    ..writeln('    screens: <MockupScreen>[');
  // The grouping key is screen + text scale + the DECLARED BANDS, not the
  // screen name alone.
  //
  // Bands are in the key because `sizes` is declared per preview while
  // `MockupScreen` models it per screen: grouping without it would union the
  // sets, so a `loading` preview asking for `compact` alone would also be
  // rendered at `expanded` because a sibling `default` preview asked for it —
  // exactly the near-identical extra PNG the field exists to prevent. Two
  // screens sharing a name but not a band set produce no filename collision,
  // because the band is part of the filename.
  //
  // Text scale is in the key because a large-text pass is a separate screen
  // entry by design; the runner tags the filename with it.
  _groupBy(previews, _screenKey).forEach((
    String _,
    List<DiscoveredPreview> states,
  ) {
    _writeScreen(out, states: states, prefixes: prefixes);
  });
  out
    ..writeln('    ],')
    ..writeln('  ),');
}

/// Everything that has to match for two previews to be states of one screen.
String _screenKey(DiscoveredPreview preview) {
  final List<String> sizes = preview.sizes.toList()..sort();
  return '${preview.screen}|${preview.textScale}|${sizes.join(",")}';
}

void _writeScreen(
  StringBuffer out, {
  required List<DiscoveredPreview> states,
  required Map<String, String> prefixes,
}) {
  final DiscoveredPreview head = states.first;
  // Every state in this group declared the same bands — that is what put them
  // in one group — so the head's are the screen's.
  final Set<String> sizes = head.sizes.toSet();
  out
    ..writeln('      MockupScreen(')
    ..writeln("        name: '${head.screen}',")
    ..writeln('        textScale: ${head.textScale},')
    ..writeln(
      "        sizes: <String>{${sizes.map((String s) => "'$s'").join(', ')}},",
    )
    ..writeln('        states: <MockupState>[');
  for (final DiscoveredPreview state in states) {
    final String prefix = prefixes[state.importUri]!;
    final String args = state.takesArguments ? 'context' : '';
    out
      ..writeln('          MockupState(')
      ..writeln("            name: '${state.state}',")
      ..writeln(
        '            build: (BuildContext context) => '
        '$prefix.${state.functionName}($args),',
      )
      ..writeln('          ),');
  }
  out
    ..writeln('        ],')
    ..writeln('      ),');
}

/// Insertion-ordered grouping, so the generated file follows the sort the
/// scanner already applied.
Map<String, List<T>> _groupBy<T>(List<T> items, String Function(T) key) {
  final Map<String, List<T>> grouped = <String, List<T>>{};
  for (final T item in items) {
    grouped.putIfAbsent(key(item), () => <T>[]).add(item);
  }
  return grouped;
}
